# Auto-generated by hatch_build.VersionWriter — committed so wheel
# builds without access to .git still ship a real version number.
COMMIT_COUNT = "316"
COMMIT_SHA = "e70b3ce87e60bdb5f25189910cdb1bc0706350e5"
