# Auto-generated by hatch_build.VersionWriter — committed so wheel
# builds without access to .git still ship a real version number.
COMMIT_COUNT = "345"
COMMIT_SHA = "5805c985f77deb10631643b284a5126fa2c089f6"
