# Auto-generated by hatch_build.VersionWriter — committed so wheel
# builds without access to .git still ship a real version number.
COMMIT_COUNT = "459"
COMMIT_SHA = "5ada0883ae968eef87ba6b715ff805997929c6cc"
